server:
  port: 8095

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/auctionHouseDB
    username: postgres
    password: admin1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
  flyway:
    baseline-on-migrate: true
    user: postgres
    password: admin1234
    schemas: public
    url: jdbc:postgresql://127.0.0.1:5432/auctionHouseDB
    locations: classpath:db/migration
  mail:
    port: 465
    test-connection: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
